const {default: strings} = require('../i18n/strings');

export const tabViewData = [strings.gamesPlayed, strings.badges];

export const badgesData = [
  {
    title: 'First Stripe Earned',
    desc: 'Top 10% of highest spending players in a month',
    multiplier: 'x 3',
  },
  {
    title: 'Born Winner',
    desc: 'Top 10% of highest spending players in a month',
  },
  {
    title: 'Trader of the Month',
    desc: 'Won 7 under-over games in a row',
  },
  {
    title: 'Rising Star',
    desc: 'Top 10% of highest spending players in a month',
  },
  {
    title: 'Jackpot',
    desc: 'Top 10% of highest spending players in a month',
  },
  {
    title: 'Impossible',
    desc: 'Top 10% of highest spending players in a month',
  },
  {
    title: 'First Stripe Earned',
    desc: 'Top 10% of highest spending players in a month',
  },
];

export const predicationData = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '31',
  '32',
  '33',
  '34',
  '35',
  '36',
  '37',
  '38',
  '39',
  '40',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
  '48',
  '49',
  '50',
];
